wallpaper {
  monitor = DP-3
  path = ~/Pictures/Wallpapers/Claude_Monet,_French_-_The_Japanese_Footbridge_and_the_Water_Lily_Pool,_Giverny_-_Google_Art_Project.jpg
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/Wallpapers/Claude_Monet,_French_-_The_Japanese_Footbridge_and_the_Water_Lily_Pool,_Giverny_-_Google_Art_Project.jpg
  fit_mode = cover
}

ipc = on
